camera:
  settings:
    - "exposure_auto=1"
    - "exposure_absolute=7"
    - "white_balance_temperature_auto=1"
    - "backlight_compensation=0"
    - "sharpness=3"
    - "brightness=0"
    - "contrast=0"
    - "saturation=90"
    - "gamma=100"
    - "gain=0"
    - "hue=0"
  gstreamer:
    width: 1280
    height: 720
    framerate: 30

